#!/bin/bash
# boe - Batch Opus Encoder
help() {
    printf "boe\n"
    printf "Usage:\n"
    printf "boe [options] -i ALBUMDIR\n"
    printf "\nOptions:"
    printf "\n-i (INPUTDIRECTORY)"
    printf "\n-o (OUTPUTDIRECTORY)"
    printf "\n-b (BITRATE)"
    printf "\n-r (RECURSIVE)\n"
    exit 1
} 1>&2

# Defaults (if something isn't specified)
set_globals() {
    shopt -s globstar > /dev/null 2>&1
    _bitrate=128
}

get_args() {
    while getopts i:o:b: option
    do
        case "${option}"
            in
            i) _in=$(realpath -e "${OPTARG}");;
            o) _out=$(realpath -e "${OPTARG}");;
            b) _bitrate="${OPTARG}";;
            *) help;;
        esac
    done
}

encode() {
    local _dir=""
    _dir=$(printf '%q\n' "$1")
    if compgen -G "${_dir}"'/*.flac' > /dev/null 2>&1
    then
        local _song_list=("$1"/*.flac) > /dev/null 2>&1
        local _dir="$2"
        printf -- '-------------------------------------------------------------\n'
        printf 'Now encoding all .flac in %s\n' "$1"
        printf -- '-------------------------------------------------------------\n'
        mkdir -p "$_dir" || \
            { printf "Failed to create subdirectory\n"; exit 1; }
            for _song in "${_song_list[@]}"
            do
                local _song_full="$_song"
                local _song="${_song##*/}"
                printf 'Encoding %s to Opus at ~%sKB/s\n' "${_song%.*}" "${_bitrate}"
                opusenc --quiet --bitrate "$_bitrate" "$_song_full" "$_dir/${_song%.*}.opus"
                printf '%s is done encoding\n' "${_song%.*}"
            done
    fi
}

recurse() {
    for _dir in "${_in:?}"/**/;
    do
        encode "$_dir" "${_dir/$_in/$_out}"
    done
}

main() {
    set_globals
    get_args "$@"
    recurse
}

main "$@"
