#!/bin/bash -e
# boe - Batch Opus Encoder
shopt -s globstar >> /dev/null

help() {
    printf "boe\n"
    printf "Usage:\n"
    printf "boe [options] -i ALBUMDIR\n"
    printf "\nOptions:"
    printf "\n-i (INPUTDIRECTORY)"
    printf "\n-o (OUTPUTDIRECTORY)"
    printf "\n-b (BITRATE)"
    printf "\n-r (RECURSIVE)\n"
    exit
}

# Defaults (if something isn't specified)
BITRATE=128

while getopts i:o:b:*r option
do
    case "${option}"
    in
    i) INPUT=$(realpath -e "${OPTARG}");;
    o) OUTPUT=$(realpath -e "${OPTARG}");;
    b) BITRATE="${OPTARG}";;
    r) RECURSIVE="true";;
    *) help;;
    esac
done

encode() {
    INPUT="$1"
    FLAC=$(ls -1 "$INPUT"/*.flac 2>/dev/null | wc -l)
    if [ $FLAC != 0 ];
    then
        printf "$SUBDIR\n"
        mkdir -p "$SUBDIR"/ || exit
        for SONG in "$INPUT"/*.flac ;
        do
            SONGNOEXT="${SONG%.*}"
            printf "Encoding ${SONGNOEXT##*/} to Opus at ~${BITRATE}KB/s\n"
            opusenc --quiet --bitrate $BITRATE "$SONG" "$SUBDIR"/"${SONGNOEXT##*/}.opus"
            printf "${SONGNOEXT##*/} is done encoding\n"
        done
    fi
}

subdir() {
    BASEINPUT="$(basename "$INPUT")"
    BASEOUTPUT="$(basename "$OUTPUT")"
    for DIR in "$1"/**/;
    do
        SUBDIR="$(printf "$(realpath "$DIR")\n" | sed -e s/"$BASEINPUT"/"$BASEOUTPUT"/ -e s/^.*"$BASEOUTPUT"/'\/'"$BASEOUTPUT"'\/'/)"
        encode "$(realpath "$DIR")"
    done
}

if [ $RECURSIVE ];
then
    subdir "$INPUT" 
else
    SUBDIR="$OUTPUT"/"${INPUT##*/}"
    encode "$INPUT"
fi
